### ISSUE TITLE
（无关sdk的一个问题）

### ISSUE THREAD

**Issue by GongT** [secken/secken-nodejs#4]
请求接口里的appid、auth_type、callback、应用key都是每次不变的，于是签名每次也不变。
那么，这么麻烦的签名机制到底有什么用？
= =。。。

其中除了应用key都是明文，算法也是公开的，key的长度也是已知的。
于是截获一个请求就可以撞出key啊。。。
安全性等价于 signature=md5(appKey)

（有没有别的地方反馈这种问题。。）

**Comment by Secbone** [comment]
先谢谢反馈~

这里的auth_type和callback实际上是可以根据业务需求每次改变的，所以其实签名也是随之变化的。

这里的签名机制是为了验证两方的数据包再发出之后有没有被第三方恶意截取并篡改的，所以其实是一个校验的作用。

至于安全性方面，签名被碰撞出来的系数确实和MD5(appKey)是一样的，但是其实 md5 碰撞的成本还是很高的，对于一个只做验证的字段来说，还是很安全的。

可以简单的算一下，20位的长度，大小写字母+数字，所以就是
Math.pow(62, 20) = 7.04423425546998e+35
嗯嗯，这么多  (｡・`ω´･)
按照每秒碰撞一亿次，大概可以算【223371202925861879429】这么多年~ 
我仿佛看到了新世界的大门~ ✪ω✪
